name: Deploy

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: ./gradlew run --no-daemon
      - uses: actions/upload-artifact@v7
        with:
          path: generated
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          repository: kr1viah/site
          ssh-key: '${{ secrets.SITE_DEPLOY_KEY }}'
      - name: Set up user for commit
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Delete old libraries index
        run: rm -rf public/libs
      - name: Download new libraries index
        uses: actions/download-artifact@v8
        with:
          path: public/libs
      - name: Commit changes
        run: |
          git add public/libs/*
          git commit -m 'Libraries index update'
          git push